enum AttendanceStatus {
  P
  AP
  L
  A
}
type AttendanceStatusCount {
  P: Int!
  AP: Int!
  L: Int!
  A: Int!
}

type Attendance {
  id: ID!
  session: String!
  status: AttendanceStatus!
  student_id: Int!
  marker: String!
}

type Query {
  attendances(status: AttendanceStatus): [Attendance]!
  attendancesByClass(class: String!, status: AttendanceStatus): [Attendance]!
  attendancesByStudent(student_id: Int!, status: AttendanceStatus): [Attendance]!
  countAttendanceByClass(class: String!, status: AttendanceStatus): Int!
  countAttendanceByStudent(student_id: Int!, status: AttendanceStatus): Int!
   countAttendanceByClassAllStatus(class: String!): AttendanceStatusCount!
  countAttendanceByStudentAllStatus(student_id: Int!): AttendanceStatusCount!
}

type Mutation {
  markAttendance(session: String!, status: AttendanceStatus!, student_id: Int!, marker: String!): Attendance
  removeAttendance(id: ID!): Boolean
}
